### ISSUE TITLE
Locked out before starting

### ISSUE THREAD

**Issue by mapleweef** [droidstealth/droid-stealth#269]
Hi guys I'm pretty new to this project but I have encountered a pretty big issue. I downloaded and installed the apk and once it was done installing it opened the gui for the app. I tried taping the tutorial video but that didn't work (I know this is a reported issue already) and then revived a text and opened my messenger before setting a pin. When trying to switch back I noticed that it was not on the recent apps list (I realize that this is the feature of the app). After much searching i found the widget to tap and open the app where it asked me for a pin. I never set a pin. I have tried just hitting enter (null pin which from looking at some of your code I thought was default pin) 1234, 00, #963 , #, *, and many more. I do think that this is an amazing piece of software but having some trouble figuring out what the default pin is or how to uninstall it so I can re-install it and set a pin. I do think this can be a major problem for future user friendliness. Maybe force the user to enter a pin upon first start up ?

**Comment by OlivierHokke** [comment]
Hey! thanks for your issue. Ye apparently we didn't properly test for this. For now, you can reinstall by going to Settings > Applications > Droid Stealth > Uninstall (or something of the sort). Then you should be able reinstall the APK.

**Comment by mapleweef** [comment]
Alright thanks! But now I have encountered another issue. None of the buttons work, apart from hitting the menu button on my phone which opens the options of "Share application" and "settings" and when I go into settings and try to go back the app crashes and I get locked out again.
