### ISSUE TITLE
Not enough bytes for iv: -1 [Can't read preferences file]

### ISSUE THREAD

**Issue by brussee** [droidstealth/droid-stealth#270]
After factory reset I seem to be able to launch the droid-stealth app only once, regardless of setting a pin, it will not go past the Loading screen upon starting.
From the trace below it seems that there is not enough memory? However the Nexus says it has 285MB RAM and 12GB internal memory available.

Creating encryption preferences                                             ~ [com.stealth.preferences.EncryptedPreferences.get@35]
Preferences exist... reading!                                               ~ [com.stealth.preferences.EncryptedPreferences.<init>@120]
GC_CONCURRENT freed 341K, 3% free 13045K/13447K, paused 2ms+3ms
Decrypting preferences file 'fileIndexReal.crypto'                          ~ [com.stealth.preferences.EncryptedPreferences$4.run@173]
Can't read preferences file 'fileIndexReal.crypto'. Not enough bytes for iv: -1 ~ [com.stealth.preferences.EncryptedPreferences$4.run@184]
We coulnd't read the preference file :(                                     ~ [com.stealth.preferences.EncryptedPreferences$3.onResult@130]

**Comment by intel478** [comment]
Rebooting the phone has no effect, only removing and re-installing the app works.
Also there is no difference in this behaviour from using the apk or the adb.

**Comment by intel478** [comment]
Using version tag 1.0 from source, _with_ the libraries that were removed during #268 this issue does NOT occur. So it seems to be related with using the latest version of the facebook conceal library.
