### ISSUE TITLE
Android.Monitor.Tashlet.A & Co?

### ISSUE THREAD

**Issue by IzzySoft** [droidstealth/droid-stealth#271]
I just uploaded the `.apk` (downloaded from the `releases/` page and renamed locally to match the new name) to VirusTotal. [Results](https://www.virustotal.com/de/file/3ee84d45206c3b4e7c905a50d33e615ddd4cc6228e5066fa73d53b3703b39d3a/analysis/1470866711/) look a bit scary. Any ideas what's behind that? All "false positives", I hope?

**Comment by alexwalterbos** [comment]
I can't really find anything about the results that came out of your analysis, so I can't really judge what the analysis is detecting. If you have some pointers to what the apk is being accused, I'd like to see them. 
It's hard to judge, but because we use some higher-than-average complexity logic to hide the files (encryption etc), I think we do trigger some false positives indeed. 
Every bit of code in that apk is available on this repository, so feel free to check everything. For what it's worth, here's my pinky promise that we didn't put any viruses in it.

**Comment by IzzySoft** [comment]
Thanks for the fast response, Alex! Unfortunately, I cannot check deeper (I'm not even an Android dev). Maybe folks at VirusTotal can lend a hand on that.

Besides, I've also tried to "google" some of the malware names from the report, but not much luck with any understandable details. What I found:

* [AVG on Android/Deng](http://www.avgthreatlabs.com/us-en/virus-and-malware-information/info/android-deng/)
* [ThreatInfo on Trojan/AndroidOS.TSGeneric](https://threatinfo.net/trojanandroidos-tsgeneric-file-has-been-identified-by-at-least-one-antivirus-engine-on-virustotal-as-malicious/) (looks more like a Windows threat)
* [AVG on Android:SpyAgent-SW](http://www.avgthreatlabs.com/us-en/virus-and-malware-information/info/android-spyagent/) (description sounds similar to the Deng one)

And sure, I did ***not*** accuse you of any malware attempts :) Maybe until this is solved, some (at least short) note in the `README.md` would be advisable?

**Comment by alexwalterbos** [comment]
Thank you for letting us know; we were unaware. This project is not being maintained by the (original) DroidStealth team anymore, but it might be picked up in the future by related teams. You're right, a notice in the README would be nice; I'll add it. 
No accusations taken, merely making myself look better on the interwebs ;) I hope you don't mind, I'll be closing this and other open issues in the same vein.

**Comment by IzzySoft** [comment]
I just wanted to let you know :) One more hint: I'd say at least AVG would be open to approaches – and have the resources to self-compile the code to re-check. They might even be glad doing so, as it would help them eliminate false positives. With some luck, others might follow suit.

Fingers crossed! As you might have seen, I've left a comment on that VirusTotal result, pointing here. I'll also leave a corresponding note [in my repo](https://android.izzysoft.de/repo), where the app [can be picked](https://android.izzysoft.de/repo/index/apk/com.stealth.android) using the F-Droid client (if the repo was added first, of course). If you managed to get it "white-listed" again, please let me know, so I can remove the latter comment :stuck_out_tongue_winking_eye:

**Comment by IzzySoft** [comment]
For fairness, just another update: I had meanwhile disabled the app in my repo, as [a later scan showed even more scary results](https://www.virustotal.com/de/file/3ee84d45206c3b4e7c905a50d33e615ddd4cc6228e5066fa73d53b3703b39d3a/analysis/). That was ~3 months ago, so I rescheduled another scan – just in case the reason were bad signatures on the engines' ends. Results got even worse: now it's 17 of 56 engines reporting infection.

So I'm afraid I'll have to remove it here. If someone picks up maintenance again, and gets the issue tackled, please drop me a note (e.g. by updating this issue once more) and I'll gladly pick up the package again.
